server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: bookRental
          uri: http://localhost:8081
          predicates:
            - Path=/bookRentals/**, 
        - id: bookManagement
          uri: http://localhost:8082
          predicates:
            - Path=/bookManagements/**, 
        - id: point
          uri: http://localhost:8083
          predicates:
            - Path=/points/**, 
        - id: view
          uri: http://localhost:8084
          predicates:
            - Path=, /lists/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: bookRental
          uri: http://bookRental:8080
          predicates:
            - Path=/bookRentals/**, 
        - id: bookManagement
          uri: http://bookManagement:8080
          predicates:
            - Path=/bookManagements/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: view
          uri: http://view:8080
          predicates:
            - Path=, /lists/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
